[build]
  command = "npm run build"
  publish = "build"

# Redirect /admin to the specified URL
[[redirects]]
from = "/admin"
to = "https://fin-tech-tee.netlify.app/admin?role=admin"

# Catch-all redirect
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[headers]
  "/*" = [
    "Cache-Control: max-age=300",
    "X-Frame-Options: DENY",
    "X-XSS-Protection: 1; mode=block",
    "X-Content-Type-Options: nosniff"
  ]
